name: zerotier-one
version: 1.2.12
summary: ZeroTier is a software-based managed Ethernet switch for planet Earth.
description: |
  ZeroTier is a software-based managed Ethernet switch for planet Earth.

  It erases the LAN/WAN distinction and makes VPNs, tunnels, proxies, and other kludges arising from the inflexible nature of physical networks obsolete. Everything is encrypted end-to-end and traffic takes the most direct (peer to peer) path available.

  This snap contains ZeroTier One, a service that provides ZeroTier network connectivity and makes joining virtual networks as easy as joining IRC or Slack channels.

  Visit ZeroTier's site for more information and pre-built binary packages. Apps for Android and iOS are available for free in the Google Play and Apple app stores.

confinement: strict
grade: stable

apps:
  zerotier-one:
    command: zerotier-one
    daemon: simple
    plugs:
      - network
      - network-bind
      - network-control

  zerotier-cli:
    command: zerotier-cli
    plugs:
      - network

  zerotier-idtool:
    command: zerotier-idtool
    plugs:
      - network

# snapcraft 2.36 does not support the top-level layout section yet,
# so enclose it in a passthrough object. When snapcraft 3.0 becomes
# available, we can move layout out of the passthrough section.
passthrough:
  layout:
    /var/lib/zerotier-one:
      bind: $SNAP_COMMON

parts:
  zerotier-one:
    plugin: make
    source: .
    build-packages:
      - build-essential
      - libc++-dev
    make-parameters:
      - CXX=g++
    filesets:
      binaries:
        - usr/sbin/zerotier-one
        - usr/sbin/zerotier-cli
        - usr/sbin/zerotier-idtool
    prime:
      - $binaries

slots:
  zerotier-control:
    interface: content
    read:
      - $SNAP_COMMON
